Simplified translator, build process, and cleaned up dependencies.

diff --git a/cncocr/templates/Makefile b/cncocr/templates/Makefile
--- a/cncocr/templates/Makefile
+++ b/cncocr/templates/Makefile
@@ -6,15 +6,35 @@ endif
 OCR_TYPE ?= x86-pthread-x86
 OCR_INSTALL=$(XSTACK_SRC)/ocr/install/$(OCR_TYPE)
 endif
+OCR_HOME=$(shell dirname `dirname $(OCR_INSTALL)`)
 
 # Try to be more compatible with the full makefiles
 ifndef ARGS
 ARGS:=$(WORKLOAD_ARGS)
 endif
 
+
 TARGET := {{g.name}}
+
+# Distributed (MPI)
+ifeq "$(OCR_TYPE)" "x86-pthread-mpi"
+CC := mpicc
+ifdef OCR_NODEFILE
+MPI_FLAGS := --machinefile $(OCR_NODEFILE)
+else ifdef OCR_NUM_NODES
+MPI_FLAGS := -np $(OCR_NUM_NODES)
+else
+$(error Must specify either OCR_NODEFILE or OCR_NUM_NODES)
+endif
+RUN := mpirun $(MPI_FLAGS) ./$(TARGET)
+# Shared memory
+else
 CC := gcc
+RUN := ./$(TARGET)
+endif
+
 CC_OPTS := -pthread
+LDFLAGS := -lm $(CC_OPTS)
 CFLAGS := -DOCR_ASSERT -g -O2 -I. -Icncocr_support -I$(OCR_INSTALL)/include -Wall $(CC_OPTS)
 
 include cncocr_support/{{g.name}}_defs.mk
@@ -24,6 +44,8 @@ SRCS := Main.c {{g.name}}.c $(CNC_OP_SRCS) $(CNC_STEP_SRCS) $(CNC_RUNTIME_SRCS)
 OBJS := $(patsubst %.c,%.o,$(SRCS))
 
 CFG_NAME ?= default.cfg
+OCR_CONFIG ?= $(OCR_INSTALL)/config/$(CFG_NAME)
+OCR_AR=$(OCR_INSTALL)/lib/libocr.a
 
 compile: $(TARGET)
 
@@ -31,16 +53,23 @@ compile: $(TARGET)
 %.o: %.c
 	$(CC) $(CFLAGS) -c $< -o $@
 
+# build the ocr runtime if needed
+$(OCR_AR):
+	echo $(OCR_HOME)
+	@[ -f "$(OCR_HOME)/ocr.dox" ] \
+		|| (echo "ERROR: Can't build OCR runtime (can't find OCR build directory)" && exit 1)
+	OCR_TYPE=$(OCR_TYPE) make -C $(OCR_HOME) install
+
 # linking - creating the executable
-$(TARGET): $(OBJS)
-	$(CC) -o $@ $(CC_OPTS) $(OBJS) $(OCR_INSTALL)/lib/libocr.a
+$(TARGET): $(OCR_AR) $(OBJS)
+	$(CC) -o $@ $(LDFLAGS) $(OBJS) $(OCR_AR)
 
 # delete binaries
 clean:
 	rm -f $(OBJS) $(TARGET)
 
 run: compile
-	OCR_CONFIG=$(OCR_INSTALL)/config/$(CFG_NAME) ./$(TARGET) $(ARGS)
+	OCR_CONFIG=$(OCR_CONFIG) $(RUN) $(ARGS)
 
 gdb: compile
-	OCR_CONFIG=$(OCR_INSTALL)/config/$(CFG_NAME) gdb ./$(TARGET) -ex "r $(ARGS)"
+	OCR_CONFIG=$(OCR_CONFIG) gdb ./$(TARGET) -ex "r $(ARGS)"
